const products=require('../../lib/paypal/products');
const paypal=require('../../lib/paypal/paypal-client');
const memoryEntitlements=new Map();
const orders=new Map();
function send(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(body));}
function name(v){return String(v||'').trim().slice(0,80);}
function product(id){return products[String(id||'')]||null;}
function grant(player,p){const k=player.toLowerCase();const list=memoryEntitlements.get(k)||[];let e=list.find(x=>x.productId===p.id);if(!e){e={productId:p.id,entitlement:p.entitlement,grantedAt:new Date().toISOString()};list.push(e);}memoryEntitlements.set(k,list);return e;}
async function createOrder(req,res){const p=product(req.body?.productId),player=name(req.body?.playerName);if(!p)return send(res,400,{ok:false,error:'unknown-product'});if(!player)return send(res,400,{ok:false,error:'player-name-required'});try{const o=await paypal.createOrder(p);orders.set(o.id,{productId:p.id,playerName:player,status:o.status});return send(res,200,{ok:true,orderID:o.id});}catch(e){console.error(e);return send(res,502,{ok:false,error:'paypal-create-failed'});}}
async function captureOrder(req,res){const orderId=String(req.body?.orderID||''),expected=String(req.body?.productId||''),player=name(req.body?.playerName),p=product(expected);if(!orderId||!p||!player)return send(res,400,{ok:false,error:'order-product-player-required'});try{const o=await paypal.getOrder(orderId),u=o?.purchase_units?.[0];if(u?.custom_id!==p.id||u?.amount?.value!==p.price||u?.amount?.currency_code!==p.currency)return send(res,409,{ok:false,error:'order-does-not-match-product'});const prior=orders.get(orderId);if(prior?.status==='COMPLETED'){const e=grant(player,p);return send(res,200,{ok:true,status:'COMPLETED',entitlement:e,entitlements:memoryEntitlements.get(player.toLowerCase())||[]});}const r=await paypal.captureOrder(orderId),c=r?.purchase_units?.[0]?.payments?.captures?.[0];if(!c||c.status!=='COMPLETED')return send(res,402,{ok:false,error:'capture-not-completed',status:c?.status||r?.status});const e=grant(player,p);orders.set(orderId,{productId:p.id,playerName:player,status:'COMPLETED',captureId:c.id});return send(res,200,{ok:true,status:'COMPLETED',entitlement:Object.assign({},e,{paypalOrderId:orderId,paypalCaptureId:c.id}),entitlements:memoryEntitlements.get(player.toLowerCase())||[]});}catch(e){console.error(e);return send(res,502,{ok:false,error:'paypal-capture-failed'});}}
function entitlements(req,res){const player=name(req.query?.player);if(!player)return send(res,400,{ok:false,error:'player-required'});return send(res,200,{ok:true,entitlements:memoryEntitlements.get(player.toLowerCase())||[]});}
function health(_req,res){send(res,200,{ok:true,service:'GEI PayPal Commerce',version:process.env.GEI_PAYPAL_VERSION||'0.1.0',environment:process.env.PAYPAL_ENVIRONMENT==='live'?'live':'sandbox',checkoutReady:Boolean(process.env.PAYPAL_CLIENT_ID&&process.env.PAYPAL_CLIENT_SECRET),webhookReady:Boolean(process.env.PAYPAL_WEBHOOK_ID)});}
async function webhook(req,res){try{if(!(await paypal.verifyWebhook(req.headers,req.body)))return send(res,400,{ok:false,error:'webhook-not-verified'});if(req.body?.event_type==='PAYMENT.CAPTURE.COMPLETED'){const id=req.body?.resource?.id,orderId=req.body?.resource?.supplementary_data?.related_ids?.order_id;if(orderId)orders.set(orderId,{status:'WEBHOOK_COMPLETED',captureId:id});}return send(res,200,{ok:true,received:true});}catch(e){console.error(e);return send(res,400,{ok:false,error:'webhook-verification-failed'});}}
module.exports={createOrder,captureOrder,entitlements,health,webhook};
