/* Node 18+ PayPal REST client. Secrets remain server-side. */
const BASE={sandbox:'https://api-m.sandbox.paypal.com',live:'https://api-m.paypal.com'};
function base(){return process.env.PAYPAL_ENVIRONMENT==='live'?BASE.live:BASE.sandbox;}
async function token(){const id=process.env.PAYPAL_CLIENT_ID,secret=process.env.PAYPAL_CLIENT_SECRET;if(!id||!secret)throw new Error('PayPal credentials are not configured.');const auth=Buffer.from(id+':'+secret).toString('base64');const r=await fetch(base()+'/v1/oauth2/token',{method:'POST',headers:{Authorization:'Basic '+auth,'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'});const b=await r.json();if(!r.ok||!b.access_token)throw new Error('PayPal OAuth failed ('+r.status+').');return b.access_token;}
async function req(path,opts){const t=await token();const r=await fetch(base()+path,Object.assign({},opts,{headers:Object.assign({'Accept':'application/json','Content-Type':'application/json',Authorization:'Bearer '+t},opts&&opts.headers||{})}));const b=await r.json().catch(()=>({}));if(!r.ok){const d=(b.details||[]).map(x=>x.description).filter(Boolean).join('; ');throw new Error('PayPal API '+r.status+': '+(d||b.message||'request failed'));}return b;}
async function createOrder(product){return req('/v2/checkout/orders',{method:'POST',headers:{'PayPal-Request-Id':'GEI-'+product.id+'-'+Date.now()+'-'+Math.random().toString(36).slice(2)},body:JSON.stringify({intent:'CAPTURE',purchase_units:[{custom_id:product.id,description:product.description,amount:{currency_code:product.currency,value:product.price}}],application_context:{brand_name:'GEI Dam Garden',user_action:'PAY_NOW',shipping_preference:'NO_SHIPPING'}})});}
async function captureOrder(orderId){return req('/v2/checkout/orders/'+encodeURIComponent(orderId)+'/capture',{method:'POST',headers:{'PayPal-Request-Id':'GEI-CAPTURE-'+orderId},body:JSON.stringify({})});}
async function getOrder(orderId){return req('/v2/checkout/orders/'+encodeURIComponent(orderId),{method:'GET'});}
async function verifyWebhook(headers,event){const p={auth_algo:headers['paypal-auth-algo'],cert_url:headers['paypal-cert-url'],transmission_id:headers['paypal-transmission-id'],transmission_sig:headers['paypal-transmission-sig'],transmission_time:headers['paypal-transmission-time'],webhook_id:process.env.PAYPAL_WEBHOOK_ID,webhook_event:event};if(!p.webhook_id)throw new Error('PAYPAL_WEBHOOK_ID is not configured.');const r=await req('/v1/notifications/verify-webhook-signature',{method:'POST',body:JSON.stringify(p)});return r.verification_status==='SUCCESS';}
module.exports={base,createOrder,captureOrder,getOrder,verifyWebhook};
